export const ENDPOINTS = {
  AUTH: '/api/v1/auth',
  USERS: '/api/v1/users',
  ADMIN_USERS: '/api/v1/admin/users',
  ADMIN_PRODUCTS: '/api/v1/admin/products',
  ADMIN_CATEGORIES: '/api/v1/admin/categories',
  ADMIN_ORDERS: '/api/v1/admin/orders',
  CATEGORIES: '/api/v1/categories',
  PRODUCTS: '/api/v1/products',
  INVENTORY: '/api/v1/inventory',
  CART: '/api/v1/cart',
  ORDERS: '/api/v1/orders',
  AI_STYLIST: '/api/v1/ai-stylist',
  VECTOR_SEARCH: '/api/v1/vector-search',
  KNOWLEDGE_GRAPH: '/api/v1/knowledge-graph',
  RECOMMENDATIONS: '/api/v1/recommendations',
  ANALYTICS: '/api/v1/analytics',
  NOTIFICATIONS: '/api/v1/notifications',
  ADMIN_NOTIFICATIONS: '/api/v1/admin/notifications',
}
