SPRING_DATASOURCE_URL: jdbc:postgresql://localhost:5430/ai_db

spring:
  config:
    import:
      - "optional:file:../.env.local[.properties]"
      - "optional:file:.env.local[.properties]"
      - "optional:file:../../.env.local[.properties]"
      - "optional:file:BE/.env.local[.properties]"
      - "optional:file:../BE/.env.local[.properties]"
